### ISSUE TITLE
Tinaroo changed the Gride Engine

### ISSUE THREAD

**Issue by zhilizheng** [zhilizheng/qsubshcom#3]
Tinaroo has moved from Torque to PBSpro.  However, it is not a standard PBSpro

The old version qsubshcom can't work properly. 

In order to run correctly:  

1. update to newest version of qsubshcom

2. add 
export PATH="/opt/pbs/bin:$PATH" 
to your ~/.bashrc
and source ~/.bashrc

3. changes:  
Have to specify the account name:
qsubshcom "echo hello" 1 1G test_hello 10:00:00 "-acct=UB-IMB-CNSG" 

-ntype can't work currently, as IT may have removed the nodetype parameters.

**Comment by zjuwhw** [comment]
Typo:

> changes:
Have to specify the account name:
qsubshcom "echo hello" 1 1G test_hello 10:00:00 "-acct=UB-IMB-CNSG"

Not "UB-IMB-CNSG", it's "UQ-IMB-CNSG"

**Comment by zhilizheng** [comment]
Thank you. It's a typo.
