### ISSUE TITLE
qsubshcom in  Westlake university 

### ISSUE THREAD

**Issue by LeonSong1995** [zhilizheng/qsubshcom#5]
Dear Zhili, 

I'm not sure whether this bug was caused by the version of  'SGE' or some specific parameter settings in the Westlake university cluster.  

Line 109: 
echo "#$ -pe **onehost** $2" >> $scriptname

echo "#$ -pe **thread** $2" >> $scriptname (WLU)

Best wishes,
Liyang

**Comment by zhilizheng** [comment]
Thanks.  This is a specific setting for SGE.  You can change it to work, since SGE is too old.

**Comment by LeonSong1995** [comment]
I see, thanks for your reply.
